name: Deploy Docker image

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
       - name: log into VPS and trigger deploy script
         uses: appleboy/ssh-action@master
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.key }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ github.event.repository.name }}
            echo "Deploying changes..."
            # Pull changes from the live branch
            git pull

            docker-compose up --build -d

            echo "Deployed!"
